"""tokens/colors.json -> lib/theme_tokens.g.dart. Run from repo root: python3 mobile/tool/build_tokens.py"""
import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
col = json.load(open(ROOT / "tokens/colors.json"))
flat = {}
def walk(o, p=""):
    if isinstance(o, dict):
        if "$value" in o: flat[p] = o["$value"]
        for k, v in o.items():
            if not k.startswith("$"): walk(v, f"{p}.{k}" if p else k)
walk(col)

def res(v, dark):
    m = re.match(r"^\{(.+)\}$", str(v))
    if not m: return v
    ref = m.group(1).replace("colors.", "")
    if dark and ref.startswith("semantic."):
        alt = "dark." + ref[len("semantic."):]
        if alt in flat: return res(flat[alt], dark)
    return res(flat[ref], dark)

WANT = ["semantic.action.primary", "semantic.action.primary-hover", "semantic.action.destructive", "semantic.action.secondary",
        "semantic.text.primary", "semantic.text.secondary", "semantic.text.tertiary", "semantic.text.on-action", "semantic.text.link",
        "semantic.surface.page", "semantic.surface.card", "semantic.surface.raised", "semantic.surface.sunken",
        "semantic.border.default", "semantic.border.strong", "semantic.border.focus", "semantic.interactive.selected-bg",
        "semantic.feedback.success-bg", "semantic.feedback.success-text", "semantic.feedback.success-icon",
        "semantic.feedback.warning-bg", "semantic.feedback.warning-text", "semantic.feedback.warning-icon",
        "semantic.feedback.error-bg", "semantic.feedback.error-text", "semantic.feedback.error-icon",
        "semantic.feedback.info-bg", "semantic.feedback.info-text"]

def name(k): return re.sub(r"[-.](\w)", lambda m: m.group(1).upper(), k.replace("semantic.", ""))
def hexd(v): return "0xFF" + v.lstrip("#").upper()

out = ["// GENERATED by mobile/tool/build_tokens.py from tokens/colors.json. Do not edit.", "import 'package:flutter/material.dart';", "",
       "class DsColors {", "  const DsColors({" + ", ".join(f"required this.{name(k)}" for k in WANT) + "});"]
out += [f"  final Color {name(k)};" for k in WANT]
for mode, dark in (("light", False), ("dark", True)):
    out.append(f"  static const {mode} = DsColors(" + ", ".join(f"{name(k)}: Color({hexd(res("{" + k + "}", dark))})" for k in WANT) + ");")
out.append("}")
(ROOT / "mobile/lib/theme_tokens.g.dart").write_text("\n".join(out) + "\n")
print("wrote mobile/lib/theme_tokens.g.dart")
