// GENERATED by mobile/tool/build_tokens.py from tokens/colors.json. Do not edit.
import 'package:flutter/material.dart';

class DsColors {
  const DsColors({required this.actionPrimary, required this.actionPrimaryHover, required this.actionDestructive, required this.actionSecondary, required this.textPrimary, required this.textSecondary, required this.textTertiary, required this.textOnAction, required this.textLink, required this.surfacePage, required this.surfaceCard, required this.surfaceRaised, required this.surfaceSunken, required this.borderDefault, required this.borderStrong, required this.borderFocus, required this.interactiveSelectedBg, required this.feedbackSuccessBg, required this.feedbackSuccessText, required this.feedbackSuccessIcon, required this.feedbackWarningBg, required this.feedbackWarningText, required this.feedbackWarningIcon, required this.feedbackErrorBg, required this.feedbackErrorText, required this.feedbackErrorIcon, required this.feedbackInfoBg, required this.feedbackInfoText});
  final Color actionPrimary;
  final Color actionPrimaryHover;
  final Color actionDestructive;
  final Color actionSecondary;
  final Color textPrimary;
  final Color textSecondary;
  final Color textTertiary;
  final Color textOnAction;
  final Color textLink;
  final Color surfacePage;
  final Color surfaceCard;
  final Color surfaceRaised;
  final Color surfaceSunken;
  final Color borderDefault;
  final Color borderStrong;
  final Color borderFocus;
  final Color interactiveSelectedBg;
  final Color feedbackSuccessBg;
  final Color feedbackSuccessText;
  final Color feedbackSuccessIcon;
  final Color feedbackWarningBg;
  final Color feedbackWarningText;
  final Color feedbackWarningIcon;
  final Color feedbackErrorBg;
  final Color feedbackErrorText;
  final Color feedbackErrorIcon;
  final Color feedbackInfoBg;
  final Color feedbackInfoText;
  static const light = DsColors(actionPrimary: Color(0xFF1F5A55), actionPrimaryHover: Color(0xFF174744), actionDestructive: Color(0xFFDC2626), actionSecondary: Color(0xFFF3F1EE), textPrimary: Color(0xFF1C1A17), textSecondary: Color(0xFF57524B), textTertiary: Color(0xFFA29C93), textOnAction: Color(0xFFFDFCFA), textLink: Color(0xFF1F5A55), surfacePage: Color(0xFFFDFCFA), surfaceCard: Color(0xFFFDFCFA), surfaceRaised: Color(0xFFFDFCFA), surfaceSunken: Color(0xFFFAF9F7), borderDefault: Color(0xFFE6E2DD), borderStrong: Color(0xFF726C64), borderFocus: Color(0xFF2F7169), interactiveSelectedBg: Color(0xFFEEF5F4), feedbackSuccessBg: Color(0xFFF0FDF4), feedbackSuccessText: Color(0xFF166534), feedbackSuccessIcon: Color(0xFF16A34A), feedbackWarningBg: Color(0xFFFFFBEB), feedbackWarningText: Color(0xFF92400E), feedbackWarningIcon: Color(0xFFD97706), feedbackErrorBg: Color(0xFFFEF2F2), feedbackErrorText: Color(0xFF991B1B), feedbackErrorIcon: Color(0xFFDC2626), feedbackInfoBg: Color(0xFFEEF5F4), feedbackInfoText: Color(0xFF123736));
  static const dark = DsColors(actionPrimary: Color(0xFF1F5A55), actionPrimaryHover: Color(0xFF174744), actionDestructive: Color(0xFFDC2626), actionSecondary: Color(0xFF2A2724), textPrimary: Color(0xFFFAF9F7), textSecondary: Color(0xFFA29C93), textTertiary: Color(0xFF726C64), textOnAction: Color(0xFFFDFCFA), textLink: Color(0xFF4F918A), surfacePage: Color(0xFF12100E), surfaceCard: Color(0xFF1C1A17), surfaceRaised: Color(0xFF2A2724), surfaceSunken: Color(0xFF0C0B0A), borderDefault: Color(0xFF2A2724), borderStrong: Color(0xFF726C64), borderFocus: Color(0xFF2F7169), interactiveSelectedBg: Color(0xFF0F2A2A), feedbackSuccessBg: Color(0xFF052E16), feedbackSuccessText: Color(0xFF86EFAC), feedbackSuccessIcon: Color(0xFF4ADE80), feedbackWarningBg: Color(0xFF451A03), feedbackWarningText: Color(0xFFFCD34D), feedbackWarningIcon: Color(0xFFFBBF24), feedbackErrorBg: Color(0xFF450A0A), feedbackErrorText: Color(0xFFFCA5A5), feedbackErrorIcon: Color(0xFFF87171), feedbackInfoBg: Color(0xFF081A1A), feedbackInfoText: Color(0xFF7FB2AB));
}
